# -*- coding: utf-8 -*-
"""Kopija bilježnice Cosmology-TD3 with CAMB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kqYH_oV8_6Bt4v-WrSKiEirkSH3m-KW3

# Centrale-Supélec - ST4 - Cosmology 2020 - TD3: Cosmic Microwave Background
Welcome this this second practicle work in cosmology. Today we will work with the. Cosmic Microwave Background

There are a few librairies we need to download and install in order to have everything working (Healpy, pypico, they will be described later). This is all done in the following cell.

You will also need at some point in this notebook to downlod some data files from the professor's Google Drive. In order to do so, you need to authenticate with you Google account, so when executing the following cell, you will be prompted at some point ti enter a verification code. In order to get it, follow these steps:
1. Click on the link that appears in blue just above the prompt for an authentification code
2. This opens a tabb in your browser where you need to choose which Google account you want to use. Select one by clicking on it
3. In this same tab, you are now propmted to allow Google SDK to access your Google account. Click on the blue "Allow" button in the bottom (no worry about this really...)
4. Now you should see appearing a pretty long code that you need to copy in your clipboard
5. Now come back to the Google Colab notebook and paste this code in the cell where you were prompted to give a code
6. You should be done !
"""

# Commented out IPython magic to ensure Python compatibility.
import sys

print("Using Python {}".format(sys.version_info[0]))

import healpy as hp

### Install pypico from Github
# import pypico
import camb

#### Reading file from Google Drive

from pylab import *
import numpy as np

# %matplotlib inline
from matplotlib import rc

rc("figure", figsize=(10, 5))
rc("font", size=12)
rc("text", usetex=False)
rcParams["image.cmap"] = "jet"

"""If the execution of the previous cell went fine, you should be all set for starting this practicle work ! Let's have fun !

If some error appears, please contact Jean-Christophe Hamilton through MS Teams...

# Theoretical Angular Power Spectra
Computing the  $C_\ell$ theoretical power spectra for a given cosmology is not a trivial task. It involves solving the Boltzmann Equation along the line of sight in order to account for all the various effects in a realistic manner. However, this is implemented in publicly available codes that allow computing the spectra for any set of cosmological parameters in a user-friendly manner with good python interfaces (CAMB https://camb.readthedocs.io/en/latest/ and CLASS https://lesgourg.github.io/class_public/class.html).

These codes are however too slow for this demonstration-course purpose: they take of the order of 1 second for a model, which implies a very long time for running MCMC chains. We will therefore rely on a very nice code called PICO (Parameters for the Impatient COsmologist http://arxiv.org/abs/astro-ph/0606709) that interpolates through a set of pre-calculated CAMB models. The execution time is very fast, but the accuracy is not as good as when directly using CAMB or CLASS. PICO is very user-friendly and all it needs is to point to the file containing the precalculated spectra: here jcset_py3.dat.

**I want to thank very warmly the PICO main developper Marius Millea for providing me with this training file which he prepared specifically for this course purpose.**

The installation and import (as pypico) of the PICO library were done in the first cell of this notebook, we just need to dowload from the professor's Google Drive the training set and load it with PICO:
"""

### Download the training set from Google Drive
# download = drive.CreateFile({'id': '17DWeh3xPec2iOXrQxNN2aKNr0uxuoahb'})
# download.GetContentFile('jcset_py3.dat')

### Import the training set into pypico
# pico = pypico.load_pico("jcset_py3.dat")

"""With PICO you can play with a number of cosmological parameters for which the training set was done. You can get the list of the cosmological parameters with the following command that displays the parameters with their default values inside a Python data structure known as a "Dictionnary"."""

# inputs = pico.example_inputs()
# print(inputs)

"""The above parameters are:
- As: Amplitude of the primordial spectrum for scalars
- ns: $n_s$ the spectral index of the primordial spectrum for scalar modes
- tau: the optical depth of reionization: probability of transmission  $\exp(-\tau)$
- ombh2: $\Omega_b h^2$ the baryonic matter density multiplied by the Hubble constant divided by 100
- omch2: $\Omega_c h^2$ the density of Cold-Dark-Matter (non baryonic matter) multiplied by the Hubble constant divided by 100
- H0: $H_0$ the Hubble Parameter
- omk: $\Omega_k$ the density of curvature
- pivot_scalar: the scale at which the scalar power spectrum has a turnaround (don't care about that... this is too technical)

Let's create a parameter dictionary with the best-fit values from the Planck ESA satellite data (https://www.cosmos.esa.int/web/planck/pla):
"""

# Leonora: Since we didnt actually import the pico example, just build an empty dictionary and put Planck data
# planck_pars = inputs.copy()
planck_pars = {}
planck_pars["As"] = np.exp(3.094) / 1e10
planck_pars["H0"] = 67.27
planck_pars["ns"] = 0.9645
planck_pars["ombh2"] = 0.02225
planck_pars["omch2"] = 0.1198
planck_pars["omk"] = 0.0
planck_pars["tau"] = 0.079

# Leonora: Instead of using pico example parameters, create CAMB parameters:
pars = camb.CAMBparams()

planck_pars

# Leonora: Create your universe
pars.set_cosmology(
    H0=planck_pars["H0"],
    ombh2=planck_pars["ombh2"],
    omch2=planck_pars["omch2"],
    omk=planck_pars["omk"],
    tau=planck_pars["tau"],
)

# Leonora
pars.InitPower.set_params(As=planck_pars["As"], ns=planck_pars["ns"])

"""And now, let's calculate a model (note that this training set only contains Temperature spectra for simplicity, so we will not play with Polarization here) and plot it. PICO outputs $D_\ell = C_\ell \times \frac{\ell(\ell+1)}{2\pi}$ which is the usual quantity that is plotted."""

# Leonora: here is the output from PICO that you got in previous TD3 with the code:
# rc('figure',figsize=(10,5))
# dl_TT = pico.get(**planck_pars)['dl_TT']
# ell = np.arange(len(dl_TT-2))+2
# clf()
# plot(ell, dl_TT)
# xlabel('$\ell$')
# ylabel('$\ell(\ell+1)C_\ell / 2\pi$')

# Leonora: to get the same with CAMB:
results = camb.get_results(pars)

# Leonora: and get the spectrum:
# if you want Dls like PICO was returning use the raw_cl boolean otherwise you get Cls
powers = results.get_cmb_power_spectra(pars, CMB_unit="muK", raw_cl=False)

# Leonora: you can see from the execution (on the left side of the cells) it takes about 8 seconds to get the spectrum

powers[
    "total"
].shape  # Leonora: the four columns should be TT, EE, BB, TE, so take the first one to get the same like the pico cell did

dl_TT = powers["total"][:, 0]

# Leonora: you can use the same code like before to plot, just the dls are now from camb
rc("figure", figsize=(10, 5))
# dl_TT = pico.get(**planck_pars)['dl_TT']
ell = np.arange(len(dl_TT - 2)) + 2
clf()
plot(ell, dl_TT)
xlabel("$\ell$")
ylabel("$\ell(\ell+1)C_\ell / 2\pi$")

"""## A plotting tip: scatter()
The matplotlib scatter() function (https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.pyplot.scatter.html) is actually very convenient in a number of situations. For instance if you want to plot many curves $y=f(x,a)$ on the same plot with $y$ as a function of $x$, each curve corresponding to a different value of $a$. It is not easy to display a colorbar correspondding to the possible values of the parameter $a$, just adding a call to scatter after plotting makes it possible...

This is demonstrated in the following example with a cosine function with varying phases:
"""

# number of phases
nphases = 10

# values of the phases
phasevalues = np.linspace(0, np.pi / 3, nphases)

# color index between 0 and 255 corressponding to each phase
thecol = (arange(nphases) * 256 / (nphases - 1)).astype(int)

# x values
x = np.linspace(0, 5 * np.pi, 1000)
for i in range(nphases):
    plot(x, np.cos(x + phasevalues[i]), color=get_cmap(rcParams["image.cmap"])(thecol[i]))
xlim(0, 5 * np.pi)
ylim(-1.1, 1.1)
xlabel("x")
ylabel("f(x)")

# the magic lines to be added
scatter(-phasevalues * 0 - 10, -phasevalues * 0 - 10, c=phasevalues)
aa = colorbar()
aa.ax.set_ylabel("Phase values")

"""## Evolution of the Angular Power Spectrum with cosmological parameters

In this section we will investigate how the CMB angular power spectrum evolves with cosmological parameters, reproducing figure similar to those shown during Lecture 4.

### Curvature
**Question 1:** You are requested to loop over 100 values of $\Omega_k$ between -0.03 and 0.03 and calculate in each case the angular power spectrum leaving all the other parameters unchanged (do not use the Planck values from above but the default ones from PICO). Display these power spectra in the same figure with the colors and colormap trick explained above.
"""

# here they need to use pico values and not planck so here is the example from PICO hardcoded:
inputs = {
    "As": 2.08e-09,
    "ns": 0.97,
    "tau": 0.055,
    "ombh2": 0.0225,
    "omch2": 0.117,
    "H0": 50,
    "omk": -0.05,
    "pivot_scalar": 0.05,
}

# Leonora: first i did it without setting lmax and all the arrays were different size, rookie mistake
pars.set_accuracy(
    AccuracyBoost=0.5,           # ODE step size: biggest speed driver, safe for TT
    lSampleBoost=1.0,            # keep at 1: coarser sampling breaks low-ell
    lAccuracyBoost=1.0,          # keep at 1: coarser integration breaks low-ell
    TimeStepBoost=0.5,
    BackgroundTimeStepBoost=0.5,
    SourcekAccuracyBoost=0.5,
    TransferkBoost=0.5,
    NonFlatIntAccuracyBoost=0.5, # safe for |omk| < 0.1
    BessIntBoost=0.5,
    BesselBoost=0.5,
    neutrino_q_boost=0.5,
)
pars.set_for_lmax(1500, lens_potential_accuracy=0)

nn = 10
paramvals = np.linspace(-0.03, 0.03, nn)

allDl = []
import time

t = time.time()
print("time : ", t)
for i in range(nn):
    print(i)
    # inputs = pico.example_inputs()
    inputs["omk"] = paramvals[i]
    # Leonora: wherever you use PICO simply use cambs functions:
    pars.set_cosmology(
        H0=inputs["H0"],
        ombh2=inputs["ombh2"],
        omch2=inputs["omch2"],
        omk=inputs["omk"],
        tau=inputs["tau"],
    )
    pars.InitPower.set_params(As=inputs["As"], ns=inputs["ns"])
    results = camb.get_results(pars)
    powers = results.get_cmb_power_spectra(pars, CMB_unit="muK", raw_cl=False)
    dl_TT = powers["total"][:, 0]
    # Leonora: if this works ill definitely write a nice function to avoid multiple lines, but this is the first try
    # allDl.append(pico.get(**inputs)['dl_TT'])
    allDl.append(dl_TT)
print("time : ", time.time() - t)
xlim(0, 1500)
ylim(0, 6000)
thecol = (arange(nn) * 256 / (nn - 1)).astype(int)
ell = np.arange(len(allDl[0] - 2)) + 2
for i in range(nn):
    ell = np.arange(len(allDl[i] - 2)) + 2
    plot(ell, allDl[i], color=get_cmap(rcParams["image.cmap"])(thecol[i]))
scatter(-paramvals, -paramvals, c=paramvals)
aa = colorbar()
aa.set_label("$\Omega_k$")
xlabel("$\ell$")
ylabel("$\ell(\ell+1)C_\ell / 2\pi$")

# Leonora: this took 12 minutes for only 10 values (instead of previous 100) and my memory
# usage was "very high" (you can see this by clicking on RAM on upper right)
# Works, but completely not feasible. even if we took only half values it would not be doable during the courseb

# Leonora: BUT pico is fast because it uses interpolation
# and doesnt really solve the spectrum every time, so why not try the same trick with CAMB

# Leonora: we already have the 10 Dls from 10 different omk. Lets interpolate from that:

# len(allDl[3])

min_len = min(len(dl) for dl in allDl)
allDl_cut = np.array([dl[:min_len] for dl in allDl])

from scipy.interpolate import interp1d

paramvals_full = np.linspace(-0.03, 0.03, 100)  # Leonora: originally omk was split into 100 points
interp = interp1d(
    paramvals, allDl_cut, axis=0, kind="cubic", fill_value="extrapolate"
)  # dont use default as its linear
allDl_interpolated = interp(paramvals_full)

nn = 100
xlim(0, 1500)
ylim(0, 6000)
ell = np.arange(len(allDl_interpolated[0] - 2)) + 2
thecol = (arange(nn) * 256 / (nn - 1)).astype(int)
for i in range(nn):
    plot(ell, allDl_interpolated[i], color=get_cmap(rcParams["image.cmap"])(thecol[i]))
scatter(-paramvals_full, -paramvals_full, c=paramvals_full)
aa = colorbar()
aa.set_label("$\Omega_k$")
xlabel("$\ell$")
ylabel("$\ell(\ell+1)C_\ell / 2\pi$")

# Leonora: nice!! not really fast but its around 12 minutes compared to 2 hours

# Leonora: trick number 2: we can also try simply lowering the accuracy of CAMB to speed up the process since its
# not so important that the results are perfect. inside parameters, you have an Accuracy section

pars

pars.set_accuracy(
    AccuracyBoost=0.5,
    lSampleBoost=1.0,
    lAccuracyBoost=1.0,
    TimeStepBoost=0.5,
    BackgroundTimeStepBoost=0.5,
    SourcekAccuracyBoost=0.5,
    TransferkBoost=0.5,
    NonFlatIntAccuracyBoost=0.5,
    BessIntBoost=0.5,
    BesselBoost=0.5,
    neutrino_q_boost=0.5,
)
pars.set_for_lmax(1500, lens_potential_accuracy=0)

"""When we change curvature density (remember the definition of curvature density, opposite to the logic: $\Omega_k=1-\left(\Omega_m+\Omega_\Lambda\right)$): in a closed Universe - negative $\Omega_k$, the opening angle of photons is larger than in a flat one, so that the sound horizon at the time of decoupling is seen at larger scales.

## Changing $H_0$

**Question 2:** Do the same but changing $H_0$ between 60 and 80 km/sec/Mpc.
"""

# Leonora: CAMB is now lowered in accuracy
nn = 10
paramvals = np.linspace(60, 80, nn)

allDl = []
for i in range(nn):
    print(i)
    # inputs = pico.example_inputs()
    # Leonora: same thing for H0
    inputs["H0"] = paramvals[i]
    pars.set_cosmology(
        H0=inputs["H0"],
        ombh2=inputs["ombh2"],
        omch2=inputs["omch2"],
        omk=inputs["omk"],
        tau=inputs["tau"],
    )
    pars.InitPower.set_params(As=inputs["As"], ns=inputs["ns"])
    results = camb.get_results(pars)
    powers = results.get_cmb_power_spectra(pars, CMB_unit="muK", raw_cl=False)
    dl_TT = powers["total"][:, 0]
    allDl.append(dl_TT)

    # allDl.append(pico.get(**inputs)['dl_TT'])

min_len = min(len(dl) for dl in allDl)
allDl_cut = np.array([dl[:min_len] for dl in allDl])
ell = np.arange(len(allDl_cut[0] - 2)) + 2

clf()
xlim(0, 1500)
ylim(0, 6000)
thecol = (arange(nn) * 256 / (nn - 1)).astype(int)
for i in range(nn):
    plot(ell, allDl_cut[i], color=get_cmap(rcParams["image.cmap"])(thecol[i]))
scatter(-paramvals, -paramvals, c=paramvals)
aa = colorbar()
aa.set_label("$H_0$")
xlabel("$\ell$")
ylabel("$\ell(\ell+1)C_\ell / 2\pi$")

# Leonora: trick number 2 doesnt work as well, but the speed does depend on the "Accuracy" parameters you lower
# i dont really know which ones can be lowered so the results are still sound (in terms of cosmology) but feel
# free to play around with them

"""We clearly see in the above plot that increasing $H_0$ shifts the spectra towards lower multipoles (larger scales). This is understandable if one remembers that the angular distance is $D_a(z)\propto \int\frac{\mathrm{d}z}{H(z)}$, therefore increasing $H_0$ means that the same strucure (here the sound horizon at the time of decoupling) is at a lower angular distance, and therefore subtends a larger angle on the sky.

## Changing baryon content
**Question 3:** Now let's change the baryon content time $h^2$ of the Universe $\Omega_b h^2$ between 0.0205 and 0.0245, while keeping the total amount of matter constant (therefore constant curvature and dark energy). We can change $\Omega_b h^2$ and leave $H_0$ constant for that.

NB: You can try to go beyond the indicated range. Unlike PICO, CAMB has no training range limitations, so the results will remain physically valid across a wide parameter space.
"""

nn = 100
paramvals = np.linspace(0.0205, 0.0245, nn)

allDl = []
for i in range(nn):
    inputs = planck_pars.copy()
    inputs["ombh2"] = paramvals[i]
    inputs["omch2"] = planck_pars["omch2"] + (planck_pars["ombh2"] - paramvals[i])
    pars.set_cosmology(H0=inputs["H0"], ombh2=inputs["ombh2"], omch2=inputs["omch2"],
                       omk=inputs["omk"], tau=inputs["tau"])
    pars.InitPower.set_params(As=inputs["As"], ns=inputs["ns"])
    results = camb.get_results(pars)
    powers = results.get_cmb_power_spectra(pars, CMB_unit="muK", raw_cl=False)
    allDl.append(powers["total"][:, 0])

xlim(0, 1500)
ylim(0, 6000)
thecol = (arange(nn) * 256 / (nn - 1)).astype(int)
for i in range(nn):
    plot(ell, allDl[i], color=get_cmap(rcParams["image.cmap"])(thecol[i]))
scatter(-paramvals, -paramvals, c=paramvals)
aa = colorbar()
aa.set_label("$\Omega_b h^2$")
xlabel("$\ell$")
ylabel("$\ell(\ell+1)C_\ell / 2\pi$")

"""As explained in the lectures, increasing baryons increases the constrast between even and odd peaks (odd peaks tend to reduce).

# CMB Maps

The CMB comes from all direcftions in the sky and we are interested in its angular power spectrum. If we want to analyse it properly, we need to handle images of the CMB (that we call "maps") that preserve its angular properties. This means dealing with the fact that it is on a sphere which has curvature with respect to usual flat projected maps that are commonly used in astronomy when dealing with small images for which curvature remains negligible. On the large angular scales involved in CMB analysis, curvature cannot be neglected and the best way to deal with it is to have our maps directly on the sphere, with an adequate pixellisation of the sphere so that we do not manipulate projected data, but only use projection for plottong purposes.

The most commonly (and almost exclusively) used sky pixellisation called Healpix (https://sourceforge.net/projects/healpix/). This is an equal area, iso-latitude pixellisation of the sphere where the numbering of the pixels obeys a simple hierarchical rule. This allows fast and efficient Spherical Harmonics transforms which is of course a very nice feature for CMB. Helpix has a nice python implementation called "Healpy".

Let's directly see what a healpix map looks like:
- there are 12 basic pixels in a Healpix map. This basic hierarchical level is known as $n_{side}=1$. They have the approximate shape of diamonds.

<img src="https://skyview.gsfc.nasa.gov/images/hpx1.jpg">

- Then they can be subdivided as many times as one wishes through the `nside` parameter and are placed on the sphere according to the following scheme.

<img src="https://healpix.jpl.nasa.gov/images/gorski_f1.jpg">

Although it is now possible to use any integer for the parameter nside, the common habit is to only use powers of 2 for nside. This is mostly inheritance of the first versions of Healpix, about 20 years ago, when nside could only be powers of two.

Helpix comes with two main projections fopr displaying the spherical maps:
- Mollweide projection for full sky viewing: https://en.wikipedia.org/wiki/Mollweide_projection. Thos projection offers a good compromise regarding preservation of shapes and proportions...
- Gnomonic projection for smaller regions: https://en.wikipedia.org/wiki/Gnomonic_projection. This projection displays great circles as straight lines, which is a nice property.
- other projections are available but less commonly used.

Let's first play with the Mollweide projection for which the healpy

In the following cell you can play with the nside parameter that you should vary nside from 1 to whatever power of two you would like to see. The number of pixels and their angular size is calculated and displayed. Beyond nside = 1024 you will really have a lot of pixels, so don't go too much beyond this...
"""

nside = 1
map = np.arange(12 * nside**2)
hp.mollview(
    map,
    title="Nside={0:} - Npix={1:} - PixSize={2:5.1f} arcmin".format(
        nside, 12 * nside**2, hp.nside2resol(nside, arcmin=True)
    ),
)

"""## Fast Spherical Harmonics Transforms with Healpix
As you remember, we are interested in the angular power spectrum of the CMB, which we obtain throught the variance of the Spherical Harmonics Transform coefficients of the map, the $a_{\ell m}$:
$$\frac{\Delta T}{T}\left(\vec{n}\right) = \sum_\ell \sum_{m=-\ell}^\ell a_{\ell m} Y_\ell^m(\vec{n})$$
(where $\vec{n}$ is a unit vector on the sphere pointing towards $(\theta,\phi)$).

Therefore:
$$a_{\ell m} = \int \frac{\Delta T}{T}\left(\vec{n}\right)Y_\ell^{m\star}(\vec{n})\mathrm{d}\vec{n}$$
The Spherical Harmonics can be split into azimuthal and zenithal parts:
$$Y_\ell^m(\vec{n}) = \lambda_\ell^m(\theta) \exp(i m\phi)$$
Therefore, when discretizing the integral to work with pixels, one has:
$$\begin{eqnarray}
a_{\ell m} &=& \int \frac{\Delta T}{T}\left(\vec{n}\right)Y_\ell^{m\star}(\vec{n})\mathrm{d}\vec{n} \\
&=& \frac{4\pi}{N_{pix}} \sum_{\mathrm{pixels}~k}  \frac{\Delta T}{T}\left(\theta_k, \phi_k\right) \lambda_\ell^m(\theta_k) \exp(i m\phi_k) \\
\end{eqnarray} $$
For each value of $\theta_k$ (zenithal angle), we make the sum over each of the $k'$ pixels over all azimuthal values:
$$\begin{eqnarray}
a_{\ell m} &=& \frac{4\pi}{N_{pix}} \sum_{\theta_k}  \lambda_\ell^m(\theta_k) \sum_{\phi_{k'}} \frac{\Delta T}{T}\left(\theta_k, \phi_{k'}\right)\exp(i m\phi_{k'})\\
&=& \frac{4\pi}{N_{pix}} \sum_{\theta_k}  \lambda_\ell^m(\theta_k) E_m(\theta_k)
\end{eqnarray}$$
where $E_m(\theta_k)$ is just the FFT (Fast Fourier Transform) of the azimuthal values of the map at a given zenith angle:
$$E_m(\theta_k) = \sum_{\phi_{k'}} \frac{\Delta T}{T}\left(\theta_k, \phi_{k'}\right)\exp(i m\phi_{k'})$$

This latter trick is the main reason for using Healpix maps instead of other pixellisations and allows fast Sherical Hamronic Transforms. A similar trick can be used to generate a pixellized map from input $a_{\ell m}$ values of course.

## Simple maps examples
Let's generate a map from its power spectrum with only one non-zero $\ell$ in order to see how scales on the sky relate to $\ell$ values. You can change `nside` and the values of $\ell$ that are set to 1. The generation of the maps is made with the built-in hp.synfast() function that generates $a_{\ell m}$ with random gaussian phases and a variance given by the input $C_\ell$. We call this a "Realization" of the power spectrum.

NB: If you run the simulation multiple times, the images will change somehow, as you make each time a new realization of the same underlying power spectrum. If you were to average between many images. with the same input power spectrum, each of them would have a slightly different power spectrum but the average would match the input one. We will play with this a bit later.
"""

rc("figure", figsize=(10, 6))
nside = 128
non_zero_ell = [5, 20, 60]

for i in range(len(non_zero_ell)):
    cell = np.zeros(3 * nside)
    cell[non_zero_ell[i]] = 1.0
    subplot(2, 3, i + 1)
    plot(cell)
    xlim(0, 100)
    xlabel("$\ell$")
    ylabel("$C_\ell$")
    themap = hp.synfast(cell, nside)
    hp.mollview(themap, sub=(2, 3, i + 4), title="$\ell={}$".format(non_zero_ell[i]))
    tight_layout()

"""## Calculating power spectra from maps:
Here we use a Planck reduced resolution map at nside=256 . Note that the map we read here has been previously cleaned for foregrounds as is discussed later in the lectures (and this is a whole research area).

"""

### Download Planck SMICA map from Google Drive
download = drive.CreateFile({"id": "1KCa1FoB8H13o497FDSZr9BXd7R2Y2DqW"})
download.GetContentFile("PlanckSmica_ns256.fits")

# read the map
themap = hp.read_map("PlanckSmica_ns256.fits")
nside = hp.npix2nside(len(themap))

# visualize it
hp.mollview(themap, min=-200, max=200, title="Planck SMICA map at nside={}".format(nside))

"""We can have a look at details of the map using the hp.gnomview() function that returns a gnomonic projection as mentionned earlier:"""

# visualize it
hp.gnomview(
    themap,
    rot=[0, 90],
    reso=20,
    min=-200,
    max=200,
    title="Planck SMICA map at naside={}".format(nside),
)

"""hp.gnomview() needs extra arguments with respect to healpix: the direction in the sky that should be at  the center with the keyword "rot" and the resolution of pixellized projection in arcminutes per image pixel with the keyword "reso".

We can directly calculate the angular power spectrum of this map using the built-in hp.anafast() function of Healpix. I recommend not calculating power spectra beyond $l_{max}=2\times nside$ as the SMICA map is slightly biased beyond and Healpix also looses significant accuracy that far in $\ell$. This is done with the kweyword lmax=2*nside added to the call to anafast(). In such a case, the returned power spectrium will have lmax+1 elements:
"""

# calculate the Cl
clplanck = hp.anafast(themap, lmax=2 * nside)
ll = arange(2 * nside + 1)
dlplanck_raw = clplanck * ll * (ll + 1) / 2 / np.pi
plot(ll, dlplanck_raw, "r.", label="Planck SMICA map")
xlim(0, np.max(ll))
legend(numpoints=1)
xlabel("$\ell$")
ylabel("$C_\ell$ (Raw)")

"""Let's now compare the angular power spectrum we just calculated from the Planck maps with the theoretical expectations from CAMB (with the Planck fitted cosmological parameters):"""

#### CAMB calculation of the theoretical power spectrum
pars.set_cosmology(H0=planck_pars["H0"], ombh2=planck_pars["ombh2"],
                   omch2=planck_pars["omch2"], omk=planck_pars["omk"], tau=planck_pars["tau"])
pars.InitPower.set_params(As=planck_pars["As"], ns=planck_pars["ns"])
results = camb.get_results(pars)
powers = results.get_cmb_power_spectra(pars, CMB_unit="muK", raw_cl=False)
dl_TT = powers["total"][:, 0]
ell = np.arange(len(dl_TT - 2)) + 2

#### Plotting both
clf()
plot(ell, dl_TT, label="CAMB Prediction")
plot(ll, dlplanck_raw, "r.", label="Planck SMICA map")
xlim(0, 2 * nside + 1)
legend(numpoints=1)
xlabel("$\ell$")
ylabel("$\ell(\ell+1)C_\ell / 2\pi$")

"""Not a big success... Something is missing here !

Indeed we did not account for two important observational effects:
- The angular resolution of Planck: as any telescope Planck does not have infinite angular resolution, it is limited by the size of the mirror and the observation wavelenght... In the case of Planck the Point-Spread-Function is well approximated by a Gaussian with a Full-Width at Half-Maximum FWHM=10 arcminutes (observing at 150 GHz with a 1 meter mirror gives 8.4 arcminutes, but additional effects sum up to 10 arcminutes). You may remember that the realtionship between FWHM and $\sigma$ is $FWHM = 2.35 \times \sigma$. The angular resolution corresponds to a convolution by a kernel in map-space and there fore a multiplication by the harmonic trasnsform of the kernel in Harmonic space (like with Fourier transforms). For a Gaussian point-spread-function with width given by $\sigma$ (angle on the sky in radians), the corresponding function in harmonic space is also a Gaussian given by:
$$B_\ell = \exp(-\frac{1}{2}\ell^2 \sigma^2)$$
Note that the $C_\ell$ being a variance, the effect of the resolution on the $C_\ell$  is a multiplication by the square of $B_\ell$.

- The pixels of the Healpix maps also smooth the real sky map as we average measurements within the area of the pixel. This is once more a convolution in map-space (by the shape of the pixels) and therefore a multiplication in Harmonic space, by a function directly. given bby the Healpix library called the "pixel window function":
```
pixwin = hp.pixwin(nside)
```
Similarly as for the angular resolution effect, the $C_\ell$ are multiplied by the square of the pixel window function.

These two effects explain why we did not find a good matching between our power spectrum measured on the Planck map and the theoretical expecations. We need to correct the measured power spectrum for the two effects we mentionned in order to have something that no longer depends on the onstrument characteristics and pixellisation scheme.

**Question 4:** Display the planck power spectrum corrected from the two effects before and see how it matches well with the theoretical prediction from PICO. Beware, the vector returned by hp.pixwin() may not have the same number of elements as your measured $C_\ell$ so you will have to deal with that...
"""

# calculate the Cl
clplanck = hp.anafast(themap, lmax=2 * nside)
ll = arange(2 * nside + 1)
bl = np.exp(-(ll**2) * np.radians(10.0 / 60 / 2.35) ** 2 / 2)
pixwin = hp.pixwin(256)[0 : len(ll)]
dlplanck = clplanck * ll * (ll + 1) / 2 / np.pi / pixwin**2 / bl**2

plot(ll, dlplanck, "r.", label="Planck SMICA map")
plot(ell, dl_TT, label="PICO Prediction")
xlim(0, np.max(ll))
legend(numpoints=1)
xlabel("$\ell$")
ylabel("$C_\ell$")

"""This much better !!

# Making a Monte-Carlo Simulation
We will now perform a Monte-Carlo simulation in order to reveal two major effects we have to deal with when working with real data:
1. Noise Bias
2. Sample Variance

In order to do so, you will simulate $N=30$ maps with the same underlying power spectrum, we will add a certain level of Gaussian white noise on the maps and calculate the power spectra of these maps, average them and calculate their variances.

So you need to write a loop over the 30 realization, make a sky realization as above, make noise map that you will add to the sky map, calculate the power spectrum and store it into a variable over which you will make average and RMS at the end. In order to reveal the effect of sample variance and noise bias, for each realization you need to calculate the power of the map without noise, with noise and the power of the noise alone.

In order to simulate random white noise use the function:
```
noise = np.random.randn(npix) * RMSnoise
```
with a RMS noise of the order of $100\mu K$.

Remember that synfast() takess $C_\ell$ as an entry, not $D_\ell$ as provided by PICO (a factor $\ell(\ell+1)/2\pi$). Additionnaly, if you want to simulate the two smoothing effects we discussed earlier in your simulated maps, you need to specifiy it to synfast with:
```
sky = hp.synfast(cl_TT, nside, pixwin=True, fwhm=np.radians(10./60))
```

**Question 5:** Perform this monte carlo simulation and calculate the average and RMS power spectra (using numpy's mean() and std() functions) for sky with no noise, sky with noise and noise only, correcting them for beam and pixel window function. Display all of the mean spectra in a plot of $\ell(\ell+1) C_\ell/2\pi$ as a function of $\ell$.

NB: you will see some disagreements at very low $\ell$ as well as a slight disagrement on the peak of the power spectrum. This is because we have not taken all subtel effects into account here, let's neglect these differences.
"""

nbmc = 30
nside = 256
lmax = 2 * nside
FWHM = 10.0  # arcminutes
RMSnoise = 100.0

### Theoreticl Cl from Dl
cl_TT = dl_TT / (ell * (ell + 1) / 2 / np.pi)

### Measured ell and correction for beam and pixel window function
ll = arange(2 * nside + 1)
bl = np.exp(-(ll**2) * np.radians(FWHM / 60 / 2.35) ** 2 / 2)
pixwin = hp.pixwin(nside)[: lmax + 1]

### empty arrays to be filled in the loop
clsky_nonoise = np.zeros((nbmc, lmax + 1))
clnoise = np.zeros((nbmc, lmax + 1))
clsky = np.zeros((nbmc, lmax + 1))

### Now the loop
for i in range(nbmc):
    print("Realization {} over {}".format(i + 1, nbmc))
    sky = hp.synfast(cl_TT, nside, pixwin=True, fwhm=np.radians(10.0 / 60))
    noise = np.random.randn(12 * nside**2) * RMSnoise
    clsky_nonoise[i, :] = hp.anafast(sky, lmax=2 * nside)
    clnoise[i, :] = hp.anafast(noise, lmax=2 * nside)
    clsky[i, :] = hp.anafast(sky + noise, lmax=2 * nside)

mean_dlsky = np.mean(clsky, axis=0) / pixwin**2 / bl**2 * ll * (ll + 1) / 2 / np.pi
sig_dlsky = np.std(clsky, axis=0) / pixwin**2 / bl**2 * ll * (ll + 1) / 2 / np.pi
mean_dlsky_nonoise = np.mean(clsky_nonoise, axis=0) / pixwin**2 / bl**2 * ll * (ll + 1) / 2 / np.pi
sig_dlsky_nonoise = np.std(clsky_nonoise, axis=0) / pixwin**2 / bl**2 * ll * (ll + 1) / 2 / np.pi
mean_dlnoise = np.mean(clnoise, axis=0) / pixwin**2 / bl**2 * ll * (ll + 1) / 2 / np.pi
sig_dlnoise = np.std(clnoise, axis=0) / pixwin**2 / bl**2 * ll * (ll + 1) / 2 / np.pi

plot(ll, mean_dlsky, ".", label="Mean Sky with no noise")
plot(ll, mean_dlsky_nonoise, ".", label="Mean Sky no noise")
plot(ll, mean_dlnoise, ".", label="Mean Noise")
plot(ell, dl_TT, label="Input $C_\ell$")
xlim(0, np.max(ll))
legend(numpoints=1)
xlabel("$\ell$")
ylabel("$C_\ell$")
ylim(0, 10000)

"""You should obtain the following result:
- The average of sky without noise should be almost unbiased except at very low $\ell$ and a slight bias near the peak of the spectrum at $\ell~200$.
- The average of the $C_\ell$ of the Sky+Noise should be significantly above the expected result.
- The average of the noise should be a quadratically increasing function of $\ell$.

### Noise Bias:
The above result is absolutely normal if you remember that your noisy sky map is the sum of the noiseless sky map and the noise map (we use vector notation for the map as there are npix pixels):
$$ \vec{m} = \vec{s}+\vec{n}$$

As a result, if we go to power spectrum, one expects:
$$C_\ell[\vec{m}] = C_\ell[\vec{s}] + C_\ell[\vec{n}]$$
In other words, you can unbias the map+noise power spectrum by removing the noise bias

Furthermore, for white noise, the noise bias can be calculated analytically and is:
$$C_\ell[\vec{n}] = \sigma^2_{noise} \times \frac{4\pi}{npix}$$

**Question 6:** Test these two relationship in the following cell: plot the difference between the Sky+Noise spectra and the noise only and show that it matches the input theoretical power spectrum (or the noiseless sky ones). Also show that the noise bias power spectrum agrees well with the above formula.
"""

th_noise_bias = (
    (RMSnoise**2 * (4 * np.pi / (12 * nside**2))) * ll * (ll + 1) / np.pi / 2 / pixwin**2 / bl**2
)

plot(ll, mean_dlnoise, ".", label="noise bias")
plot(ll, th_noise_bias, label="Model for noise bias")
plot(ll, mean_dlsky - mean_dlnoise, ".", label="Debiased Observed $C\ell$")
plot(ell, dl_TT, label="Input $C_\ell$")
xlim(0, np.max(ll))
legend(numpoints=1)
xlabel("$\ell$")
ylabel("$C_\ell$")
ylim(0, 10000)

"""You should obtain a much better agreement with the input model (as good as what you obtained without noise).

### Studying the RMS of the power spectra

One can predict the behaviour of the uncertainties, there are two contribution:
1. variance from noise: the noise you added not only adds power to the power spectrum but also has fluctuations around this mean noise bias.
2. sample variance: the noiseless sky itself has varied among the realization as each time you run synfast() you draw new random realizations of $a_{\ell m}$. Only their variance is on average that of the input power spectrum. So for a given sky realization (for instance the one we observe from Earth) we expect that this sky has some so called "sample-variance" with respect to the "true underlyong power spectrum" that you could only get from observing an infinite number of CMB realizations, or from an infinite number of locations in the Universe.

These two effects actually follow the same very simple law that can be derived in the following manner:
- the $C_\ell$ is a variance at a given $\ell$ over $a_{\ell m}$ whose distribution is Gaussian with average zero by construction. There are $2\ell +1$ values of $m$ for each $\ell$. So this means that in order to calculate our empirical $C_\ell$, we average the modulus square of the $a_{\ell m}$ over these $2\ell+1$ possibles $m$ values:
$$C_\ell = Var(a_{\ell m}) = \frac{1}{2\ell+1} \sum_{m=-\ell}^{\ell} \left| a_{\ell m}\right|^2$$
- If a random variable $x$ is gaussian distributed with variance $\sigma^2$ then the random variable $x/\sigma$ is normal distrubuted and summing squares of realizations of this variable $\sum_n x_i^2/\sigma^2$ is $\chi^2$-distributed with $n$ degree of freedom and therefore has variance $Var(\sum_n x_i^2/\sigma^2)=2n$. Therefore we have:
$$Var(\sum_n x_i^2) = 2n\sigma^4$$
as a consequence
$$\begin{eqnarray}
Var(\frac{1}{n} \times \sum_n x_i^2) &=& \frac{1}{n^2}\times 2n\times\sigma^4 \\
&=& \frac{2}{n}\sigma^4 \\
&=& \frac{2}{n}\times Var(x)^2
\end{eqnarray}$$
So one can apply that to the $C_\ell$ formula above:
$$Var\left(\frac{1}{2\ell+1} \sum_{m=-\ell}^{\ell} \left| a_{\ell m}\right|^2\right) = \frac{2}{2\ell+1}\times Var(a_{\ell m})^2$$
Applied to the variance of the $C_\ell$ we get:
$$Var(C_\ell) = \frac{2}{2\ell+1} C_\ell^2$$
and so the RMS on the $C_\ell$ shoud be:
$$RMS[C_\ell] = \sqrt{\frac{2}{2\ell+1}}\times C_\ell$$

This applies to both the signal and noise power spectra and the total RMS is the sum of both.

**Question 7:** Now plot in the following cell the RMS of your Monte-Carlo power spectra and the expected behaviour from the above considerations. You will see an excellent agreement.
"""

sample_variance_rms = dl_TT[: lmax + 1] * np.sqrt(2.0 / (2 * ll + 1))
noise_variance_rms = th_noise_bias * np.sqrt(2.0 / (2 * ll + 1))


plot(ll, sig_dlsky, ".", alpha=0.5, label="Sky with Noise")
plot(ll, sig_dlnoise, ".", alpha=0.5, label="Noise")
plot(ll, sig_dlsky_nonoise, ".", alpha=0.5, label="Sky No Noise")
plot(ll, sample_variance_rms, lw=2, label="Signal Sample variance RMS")
plot(ll, noise_variance_rms, lw=2, label="Noise RMS")
plot(ll, sample_variance_rms + noise_variance_rms, lw=2, label="Total RMS")
ylim(0, 700)
legend()
xlabel("$\ell$")
ylabel("$C_\ell$")

"""END of TD3"""
