name: CD

on:
  push:
    branches:
     - main

jobs:
  docs:
    name: Deploy API Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: python -m pip install myst-parser numpy numpydoc sphinx sphinx_rtd_theme

      - name: Build API documentation
        run: |
            rm -rf docs/source/*.rst  
            sphinx-apidoc -Mfeo sphinx_documentation/Documentation_test/docs/source sphinx_documentation/Documentation_test/mycosmo
            sphinx-build sphinx_documentation/Documentation_test/docs/source sphinx_documentation/Documentation_test/docs/build

      - name: Deploy API documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
